kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: digital-wallet-build-gh-runner
  namespace: digital-wallet-build
subjects:
  - kind: ServiceAccount
    name: gh-runner
    namespace: mathianasj-backstage-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
