---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eda-demo-dev
  namespace: eda-demo-build
subjects:
  - kind: ServiceAccount
    name: default
    namespace: eda-demo-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eda-demo-qa
  namespace: eda-demo-build
subjects:
  - kind: ServiceAccount
    name: default
    namespace: eda-demo-qa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eda-demo-prod
  namespace: eda-demo-build
subjects:
  - kind: ServiceAccount
    name: default
    namespace: eda-demo-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'
